services:
    exozet_grunt.cache_warmer:
        class: Exozet\GruntBundle\CacheWarmer\GruntCacheWarmer
        arguments:
            - '@kernel'
            - '@logger'
        tags:
            - { name: kernel.cache_warmer }

